language: ruby
rvm:
  - 2.1.0
env:
  - USE_SYSTEM_GECODE=1
addons:
  apt:
    packages:
    - libgecode-dev
install:
  - bundle install --path vendor --binstubs
script:
  - bin/berks install
  - bin/rake style spec
sudo: false
